### ISSUE TITLE
Blocking for a period of time.

### ISSUE THREAD

**Issue by elecktron3d** [h-mdm/hmdm-server#10]
It is possible to block the android os and ask for a password key every month for example? and also needs to works offline.
thanks.

**Comment by h-mdm** [comment]
Headwind MDM allows the user to work offline. 

Unfortunately we cannot accept the feature of blocking the Android OS and asking for a password key every month. Headwind MDM Community does not include any locking. You can however fork a project and implement this feature. Here is how to: [https://qa.h-mdm.com/1918/](https://qa.h-mdm.com/1918/)
