### ISSUE TITLE
Self signed certificated and app error ERROR TAG: trust_anchor

### ISSUE THREAD

**Issue by renellis** [h-mdm/hmdm-server#100]
I have setup headwind on a docker compose and I'm using ha-proxy with a local CA that I use for all my certificate.

Everything works except the app that is refusing to accept the connection to the server, I assuming because the CA isn't present on whatever the app uses. Any help?

**Comment by h-mdm** [comment]
Custom CA certificates must be embedded in the Headwind MDM launcher code. See details here: https://qa.h-mdm.com/17481/add-custom-certificates-to-headwind-mdm
