### ISSUE TITLE
Failed to run task: 'grunt resolve' failed

### ISSUE THREAD

**Issue by DVNghiem** [h-mdm/hmdm-server#105]
I am currently having this error when building hmdm with docker with the configuration of using image ubuntu:20.04 and installing tomcat9.0.40 but currently having this error:

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:grunt (install js libs) on project server: Failed to run task: 'grunt resolve' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:grunt (install js libs) on project server: Failed to run task`

Please help me!

**Comment by NTL2706** [comment]
Try checking if you have downloaded the git library. I had the same problem yesterday.

**Comment by DVNghiem** [comment]
It worked, thanks @NTL2706
