### ISSUE TITLE
how to adjust time interval for status change

### ISSUE THREAD

**Issue by GaneshRamKumar** [h-mdm/hmdm-server#11]
i want status( online / offline) update with in 5 min how can i change it . now it is working but it is update time take more then one hour.

**Comment by h-mdm** [comment]
In the current version, the interval cannot be changed. This feature may be implemented in further versions of the product.

**Comment by GaneshRamKumar** [comment]
No sir ,actually in feb month we change it. change the time interval by edit some file in coding path it is working. could you tell me witch file is  running. i forget the path

**Comment by h-mdm** [comment]
You can change the status change intervals (green / yellow / red) in common/src/main/java/com/hmdm/persistence/mapper/DeviceMapper.xml

Search for 'green', there are two places where the intervals are setup (2 hours for green, 4 hours for yellow).

**Comment by GaneshRamKumar** [comment]
sorry sir  i could not find the time limt

there is no like this file common/src/main/java/com/hmdm/persistence/mapper/DeviceMapper.xml

but i am search 'green'. it is only located on this file. i am  attached with this mail kindly can you tell me where i can find time interval

**Comment by GaneshRamKumar** [comment]
i found this 
app/components/main/controller/devices.controller.js

how can i change it for 5 min

 const updateTime = 2 * 60 * 60 * 1000;
        $scope.getDeviceIndicatorImage = function (device) {
            if (device.statusCode) {
                return "images/circle-" + device.statusCode + ".png";
            } else {
                // This is an old approach but it is left for now just in case
                if ((new Date().getTime() - device.lastUpdate) < updateTime) {
                    return 'images/online.png';
                } else if ((new Date().getTime() - device.lastUpdate) < (2 * updateTime)) {
                    return 'images/away.png';
                } else {
                    return 'images/offline.png';
                }
            }
        };

**Comment by h-mdm** [comment]
This is an old approach as stated by the comment. Changing this code will not change the behaviour.

Here is the file: https://github.com/h-mdm/hmdm-server/blob/master/common/src/main/java/com/hmdm/persistence/mapper/DeviceMapper.xml

and this code needs to be changed (there are two entries of similar code):

CASE
                   WHEN (EXTRACT(EPOCH FROM NOW()) * 1000 - devices.lastupdate) &lt; (2 * 3600 * 1000) THEN 'green'
                   WHEN (EXTRACT(EPOCH FROM NOW()) * 1000 - devices.lastupdate) &lt; (4 * 3600 * 1000) THEN 'yellow'
                   ELSE 'red'
               END AS statusCode

2 * 3600 * 1000 is 2 hours in milliseconds.

**Comment by GaneshRamKumar** [comment]
ya i understand but this file i don't have it sir

i am follow this page for installation process
https://h-mdm.com/installation/

so this file are not there. what i can do?

**Comment by h-mdm** [comment]
The interval can only be changed when you build the system from the source codes. Otherwise, the interval cannot be changed. See readme.md for build instructions.

**Comment by GaneshRamKumar** [comment]
so i want use this build for change interval.
i mean i need to reinstall using this repos file 
run ./hmdm_install.sh again
before i want change the code like u mention devicemaper.xml
so it can change the time interval right?

what is the measurement for 5 min? can you tell me
300 * 1000 or
5/60 * 1000 or
5 * 1000

**Comment by GaneshRamKumar** [comment]
working thanks sir
