### ISSUE TITLE
hmdm server isn't showing interface anymore

### ISSUE THREAD

**Issue by theoneandonly-vector** [h-mdm/hmdm-server#19]
I'm runing it on ubuntu 20.04 using tomcat9 and I don't have any errors in my log file under /var/log/tomcat9/catalina.year-month-day.log and catalina.out

I can access the site but it just is a a blank page.
also service-status looks fine. is there any furthe rway to debug?

**Comment by h-mdm** [comment]
If you see a blank page but do not have any errors in Tomcat logs, the error is in the front-end application.

Clear the browser cache and reload the page, sometimes it helps.

If it doesn't help, you need to debug it using the browser developer console. To open the developer console in Chrome, click ... at the top right of the screen, then More tools - Developer tools. Click the "Console" tab and there should be some errors.

**Comment by theoneandonly-vector** [comment]
I got this error when checking "console"

´´´
throw $injectorMinErr('nomod', "Module '{0}' is not available! You either misspelled " +
             "the module name or forgot to load it. If registering a module ensure that you " +
             "specify the dependencies as the second argument.", name);
        }

[$injector:nomod] Module 'headwind-kiosk' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument
´´´

I think it might be a permissions issue but can't find where.

**Comment by h-mdm** [comment]
'headwind-kiosk' is the main app module defined in app.js. Did you change anything in the code? You may need to check the JavaScript syntax.

**Comment by theoneandonly-vector** [comment]
there was no change in the code

**Comment by h-mdm** [comment]
I perform additional check of the latest version from the repository (3.45), it doesn't have any issues like you reported.

The version of Tomcat 9 delivered by default with Ubuntu 20.04 has issues with HTTPS/SSL. To fix the Tomcat issues, you need to upgrade to the latest version manually. 

The recommended platform is Ubuntu 18.04 and Tomcat 8.

If you are using HTTPS, you need to use port 443 (or 8443), not 80 and 8080. 

To debug your issue, you can look into the "Network" tab of the Chrome developer console. Perhaps some required files are not being downloaded.

**Comment by theoneandonly-vector** [comment]
is there somehting oustide ROOT.war I can check? because the problem can't be from it. as I just copied it over 1:1 from a fresh install.

**Comment by theoneandonly-vector** [comment]
"is there somehting oustide ROOT.war I can check?" or do I need to start from scratch? // is there a way to remove everything and set it up as if it was a new server?

**Comment by h-mdm** [comment]
Here's an instruction how to remove Headwind MDM from the server: https://qa.h-mdm.com/1413/

**Comment by theoneandonly-vector** [comment]
thx

**Comment by theoneandonly-vector** [comment]
somehow this isn't enough.

**Comment by theoneandonly-vector** [comment]
it's just IE
