### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by yule-sun** [h-mdm/hmdm-server#25]
I followed the steps on this website（https://h-mdm.com/advanced-web-panel-installation/） to install it.
My OS_Version:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
There are no errors in the previous steps, only errors occurred when the script ./hmdm_install.sh was executed.
![image](https://user-images.githubusercontent.com/37107125/102946387-7415d500-44fb-11eb-9848-a383147741d6.png)
All configurations use the default settings, only the configuration item Domain name or public IP is changed to my IP address.
But after the script was executed, such an error ：
“
Deploying hmdm-3.28.4-os.war to Tomcat: /var/lib/tomcat9/webapps//hmdm.war
........................................................................................................................
ERROR: failed to deploy WAR file!
Please check /var/lib/tomcat9/logs/catalina.out for details.
”
![image](https://user-images.githubusercontent.com/37107125/102946475-be975180-44fb-11eb-978b-ef6e59b96bb4.png)
And i cann't found the file /var/lib/tomcat9/logs/catalina.out，but there is a file named catalina.2020-12-23.log  in this floder,and Its content is like this.I don't know what happened, I really need your help，thank you verymuch.
root@zz-sm-mdm:/home/yule/hmdm-install# cat /var/lib/tomcat9/logs/catalina.2020-12-23.log 
23-Dec-2020 00:39:16.216 INFO [http-nio-8080-exec-15] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0xff0xf40xff0xfd...]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
23-Dec-2020 00:46:53.278 INFO [Catalina-utility-1] org.apache.catalina.startup.HostConfig.undeploy Undeploying context [/hmdm]
23-Dec-2020 00:47:03.283 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/etc/tomcat9/Catalina/localhost/hmdm.xml]
23-Dec-2020 00:47:06.759 INFO [Catalina-utility-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Dec-2020 00:47:12.131 INFO [Catalina-utility-2] nonapi.io.github.classgraph.classloaderhandler.lifecycle.ServletLifeCycleListener.contextInitialized Servlet context initialized
23-Dec-2020 00:47:14.103 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/etc/tomcat9/Catalina/localhost/hmdm.xml] has finished in [10,819] ms
![image](https://user-images.githubusercontent.com/37107125/102946545-eedef000-44fb-11eb-814b-584c5799a067.png)

**Comment by h-mdm** [comment]
Thank you for the detailed report!

Please do not use tomcat9 with Ubuntu 18.04. The Tomcat 9 installed by apt has an HTTPS issue. Use tomcat8 instead, it works stable.

To downgrade Tomcat, use the following commands:

apt remove tomcat9
apt install tomcat8

After that, remove Headwind MDM (see the link how to: https://qa.h-mdm.com/1413/) and reinstall it. I recommend you to download the latest version from the [website ](https://h-mdm.com/download/) (the latest today is 3.30).

If you still wish to use Tomcat 9, please update it manually (see https://h-mdm.com/advanced-web-panel-installation/ section 1, red sentence) to the latest version. Also, do not install into /opt/hmdm directory, use /var/lib/tomcat9/work instead as suggested by the installer.
