### ISSUE TITLE
bug - knox plugins not provided

### ISSUE THREAD

**Issue by JulienChampseix** [h-mdm/hmdm-server#31]
On fresh install : 
- hmdm web panel version : 3.33.1
- hmdm android app version : 3.59
- OS : Ubuntu 20.04.2 LTS

Getting 500 (http code)  on page for generete QR code hmdm/rest/public/qr/XXXXXX?size=309&deviceId=XXX

checking inspector look like knox dependency missing (getting an 404 http error code) : /hmdm/app/components/plugins/knox/knox.module.js

**Comment by h-mdm** [comment]
Fixed in v3.34.1.
