### ISSUE TITLE
QR code and ID issue 

### ISSUE THREAD

**Issue by pong106** [h-mdm/hmdm-server#37]
Specification:
- serving using http
- ubuntu server

1.  Having error with devices QR and Configuration QR codes when i click to show them. The error are as below.
This site can’t be reached 
refused to connect.
2. ID is not registered when i specify the Device Number (Portal) as the ID in the mobile app.
It seems like some configuration error?

**Comment by h-mdm** [comment]
Can you please add the images of your issue?

Maybe this article is related to your issue: https://qa.h-mdm.com/1/i

**Comment by pong106** [comment]
Thanks. got it working after redirecting port 80 to 8080

**Comment by sakibguy** [comment]
Fast fixed, responsive community. Pleasure!
