### ISSUE TITLE
Add PrintSpooler and TaskManager as default application

### ISSUE THREAD

**Issue by redoo-networks** [h-mdm/hmdm-server#38]
Hy,

There are 2 default android applications, which are helpful to be added as default system applications:

com.android.printspooler - Print document
com.sec.android.app.launcher - Task manager

This would simplify first setup for new users.

Regards,
Stefan

**Comment by h-mdm** [comment]
The issue has been fixed in version 5.04.4. Also, more system packages were added to the default configuration.
