### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by howudodat** [h-mdm/hmdm-server#4]
is it possible to reset the admin password?  if so,, how?

**Comment by h-mdm** [comment]
There is currently no such function in the web UI. Thank you for the feature request, we consider to add it in further releases.

**Comment by howudodat** [comment]
can it be done at the command line?  or directly with postgres?

**Comment by h-mdm** [comment]
It can be done directly with postgres. 
UPDATE users SET password=MD5('newpassword') WHERE login='admin';

**Comment by howudodat** [comment]
thank you!
