### ISSUE TITLE
No status update on devices (All Red Dots)

### ISSUE THREAD

**Issue by Byteschmiede** [h-mdm/hmdm-server#40]
Hello!

We have installed the community edition on our system. Everything is working fine and we don't have any issues. Apps can be deployed and everything works fine... but on the web interface every device state is red and we can't figure out why.
![Bildschirmfoto 2022-01-11 um 15 21 35](https://user-images.githubusercontent.com/7261828/148960708-6d0413ab-2a75-4aa7-a07e-f1f782c01f39.png)

It's important for us the see the battery state but this is also not updating. 

Any ideas how to fix that?

**Comment by Byteschmiede** [comment]
`Jan 11 15:01:19 server tomcat9[3291626]: 2022-01-11 15:01:19 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33718 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33718
Jan 11 15:05:18 server tomcat9[3291626]: 2022-01-11 15:05:18 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:36902 failed: org.apache.activemq.transport.InactivityIOException: CONNECT frame not received with in connectionTimeout (>30000): tcp://OUR_IP_ADRESS:36902
Jan 11 15:07:19 server tomcat9[3291626]: 2022-01-11 15:07:19 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33874 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33874
Jan 11 15:07:48 server tomcat9[3291626]: 2022-01-11 15:07:48 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:36906 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:36906
Jan 11 15:11:23 server tomcat9[3291626]: 2022-01-11 15:11:23 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33898 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33898
Jan 11 15:11:24 server tomcat9[3291626]: 2022-01-11 15:11:24 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:36910 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:36910
Jan 11 15:14:01 server tomcat9[3291626]: 2022-01-11 15:14:01 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:36912 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:36912
Jan 11 15:17:06 server tomcat9[3291626]: 2022-01-11 15:17:06 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33900 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33900
Jan 11 15:17:08 server tomcat9[3291626]: 2022-01-11 15:17:08 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:36914 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:36914
Jan 11 15:21:21 server tomcat9[3291626]: 2022-01-11 15:21:21 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33902 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33902
Jan 11 15:27:08 server tomcat9[3291626]: 2022-01-11 15:27:08 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33904 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33904
Jan 11 15:29:37 server tomcat9[3291626]: 2022-01-11 15:29:37 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33908 failed: java.io.EOFException
Jan 11 15:37:06 server tomcat9[3291626]: 2022-01-11 15:37:06 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33910 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33910
Jan 11 15:39:36 server tomcat9[3291626]: 2022-01-11 15:39:36 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33912 failed: java.io.EOFException
Jan 11 15:42:07 server tomcat9[3291626]: 2022-01-11 15:42:07 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33914 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33914
Jan 11 15:47:06 server tomcat9[3291626]: 2022-01-11 15:47:06 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33916 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33916
Jan 11 15:49:26 server tomcat9[3291626]: 2022-01-11 15:49:26 [INFO] com.hmdm.notification.guice.module.NotificationTaskModule$MessagePurgeWorker : Starting the iteration ...
Jan 11 15:49:26 server tomcat9[3291626]: 2022-01-11 15:49:26 [INFO] com.hmdm.notification.guice.module.NotificationTaskModule$MessagePurgeWorker : Finished the iteration.
Jan 11 15:49:37 server tomcat9[3291626]: 2022-01-11 15:49:37 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33918 failed: java.io.EOFException
Jan 11 15:52:08 server tomcat9[3291626]: 2022-01-11 15:52:08 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33924 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33924
Jan 11 15:56:13 server tomcat9[3291626]: 2022-01-11 15:56:13 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33926 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://OUR_IP_ADRESS:33926
Jan 11 15:59:37 server tomcat9[3291626]: 2022-01-11 15:59:37 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://OUR_IP_ADRESS:33934 failed: java.io.EOFException`

Hmm does this have anything to do with it?

**Comment by Byteschmiede** [comment]
We have logged the android tablet and found something interesting:


`01-11 15:12:57.714 25421 25421 W m.hmdm.launcher: type=1400 audit(0.0:25512): avc: denied { ioctl } for pid=25421 path="/proc/25421/rtg" dev="proc" ino=9022709 ioctlcmd=0xab1e scontext=u:r:untrusted_app:s0:c124,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c124,c256,c512,c768 tclass=file permissive=0
01-11 15:12:57.719  1300  1865 W DevicePolicyManager: Package com.hmdm.launcher (uid=10124, pid=25421) cannot access Device IDs
01-11 15:12:57.719  1300  1865 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.hmdm.launcher:getSerial:isPreinstalled=false:isPrivApp=false
01-11 15:12:57.720 25421 25421 W HeadwindMDM: Failed to get serial number from Build.getSerial()
01-11 15:12:57.720 25421 25421 W System.err: java.lang.SecurityException: getSerial: The user 10124 does not meet the requirements to access device identifiers.
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Parcel.createException(Parcel.java:2077)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Parcel.readException(Parcel.java:2045)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Parcel.readException(Parcel.java:1993)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage(IDeviceIdentifiersPolicyService.java:194)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Build.getSerial(Build.java:190)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.hmdm.launcher.util.DeviceInfoProvider.getSerialNumber(DeviceInfoProvider.java:230)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.hmdm.launcher.ui.BaseActivity.createAndShowInfoDialog(BaseActivity.java:351)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.hmdm.launcher.ui.MainActivity.onClick(MainActivity.java:2398)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.view.View.performClick(View.java:7217)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.view.View.performClickInternal(View.java:7191)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.view.View.access$3500(View.java:828)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.view.View$PerformClick.run(View.java:27679)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Handler.handleCallback(Handler.java:900)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.os.Looper.loop(Looper.java:219)
01-11 15:12:57.720 25421 25421 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
01-11 15:12:57.720 25421 25421 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
01-11 15:12:57.720 25421 25421 W System.err: Caused by: android.os.RemoteException: Remote stack trace:
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:420)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.telephony.TelephonyPermissions.checkReadDeviceIdentifiers(TelephonyPermissions.java:352)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:277)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:254)
01-11 15:12:57.720 25421 25421 W System.err: 	at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:115)
01-11 15:12:57.720 25421 25421 D HeadwindMDM: Build.SERIAL=unknown
`


Maybe the app runs into an error and can't fire the request.

**Comment by h-mdm** [comment]
The transport connection messages are not related to the subject, they are related to Push notifications.

In the second log, I see that the device cannot get the serial number. This may happen if a device has no device owner rights. If you're using the serial number as a device number, this may cause a failure like yours (but in that case, you won't be able to get the settings).

How do you set up the device? Are you using the recommended way with the QR code (https://h-mdm.com/quick-start/#device), or set up in some other way? Can you paste a sample QR code here?

**Comment by Byteschmiede** [comment]
`{
"android.app.extra.PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME":"com.hmdm.launcher/com.hmdm.launcher.AdminReceiver",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION":"https://mdm.accelery.dev/files/hmdm-4.17-os.apk",
"android.app.extra.PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM":"pdTtOKT1DXmjN8dW5VHjsC934wLmtGl7dtkqAgt9Bcg=",
"android.app.extra.PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED":true,
"android.app.extra.PROVISIONING_SKIP_ENCRYPTION":true,
"android.app.extra.PROVISIONING_ADMIN_EXTRAS_BUNDLE": {"com.hmdm.DEVICE_ID":"tablet02","com.hmdm.BASE_URL":"http://mdm.accelery.dev",
"com.hmdm.SERVER_PROJECT":""}
}
`

**Comment by Byteschmiede** [comment]
But i guess its the APK which runs into an error while getting system info.
The stacktrace i posted above contains following problem:
https://stackoverflow.com/questions/56730796/unique-identifier-in-android-q

Maybe since the app throws this error, it won't fire the rest request correct?

**Comment by Byteschmiede** [comment]
![Bildschirmfoto 2022-01-12 um 08 42 21](https://user-images.githubusercontent.com/7261828/149084661-0d332695-00cf-44fa-8610-d997cab08a79.png)

This is the logcat output when MainActivity.sendDeviceInfoAfterReconfigure gets called

**Comment by h-mdm** [comment]
Thank you for the details. Even since the app can't get IMSI, it should send the device info. 

I just noticed that the BASE_URL in your QR code contents is wrong: http://mdm.accelery.dev (should be https://mdm.accelery.dev). Please update the BASE_URL in the Tomcat configuration (/var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml), restart Tomcat, and re-enroll a test device.

**Comment by Byteschmiede** [comment]
I've changed the base url right now and deleted all test devices and create new ones via QR Code but its still not updating the state. Same behavior as before. Is there any log to watch incoming API Requests on the tomcat?

**Comment by Byteschmiede** [comment]
Alright now we have fixed the issue!

We had to go to admin settings in launcher
