### ISSUE TITLE
Knox download config error

### ISSUE THREAD

**Issue by guigsilva** [h-mdm/hmdm-server#41]
Hello,

We are trying to use this to our 150 school tablets. We made a test install following https://h-mdm.com/advanced-web-panel-installation/ all ok the server is online qrcode generating ok

So we follow https://h-mdm.com/knox-mobile-enrollment/ to enrol the tablets (all samsung)

All ok on enrol the tablet but when start the UI get the msg 
"Failed to get Knox config from https://+++++++. There is a network error or an old web panel version. Make sure web panel is set up properly and has a Knox plugin

Our install :
Ubuntu 20.04
Knox plugin hmdm-3.65-knox
How can I confirm the webpanel version?

Thanks in advance
Guilherme

**Comment by h-mdm** [comment]
We are sorry but Knox version is available in Premium package only. We should have mention that on the website and we will update it soon to avoid confusing users!

**Comment by guigsilva** [comment]
Hello no kiosk mode too right?

**Comment by h-mdm** [comment]
Yes, you're right. Here's the comparison of Free and Premium packages: https://h-mdm.com/headwind-mdm-version-comparison/
