### ISSUE TITLE
How i Can block App Like Samsung Knox

### ISSUE THREAD

**Issue by alisakkaf** [h-mdm/hmdm-server#50]
hello .. i am using Common - Minimal H-MDM 
I am go to configurations/Details/Applications
And Add New App Type name and Package ID
Iam Making Version 0 cuz is system apps 
then Check System to Hide URL & File 
After Save Ask Me For Actions and iam select Block
When Scan QR And Device Finish Setup ..
Knox Container Agent Pop and Ask Me Reset Device ..
How i can fix that and block any app i want 
iam use Your Apk without any edit ..
Any Advice Bro

And Also KG LOCK Not Work ... 
How i can solve that

**Comment by h-mdm** [comment]
Sorry but your inquiry is very unclear. Anyway, Headwind MDM Community has no option to block third party apps. You can ask for the demo of Headwind MDM Premium on the website: https://h-mdm.com/
