### ISSUE TITLE
Unable to install in Ubuntu server 

### ISSUE THREAD

**Issue by navaneeth2022** [h-mdm/hmdm-server#53]
MDM Server - Failure.

Total time:  3.523 s
[INFO] Finished at: 2022-07-29T11:51:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.7:copy-resources (copy-resources) on project server: Error loading property file 'build.properties': /home/ubuntu/hmdm-server/server/build.properties -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :server

![SS2](https://user-images.githubusercontent.com/110236503/181753816-6311c762-07e3-4b32-976b-f19eff74d65d.png)

**Comment by h-mdm** [comment]
Please read BUILD.txt for build instructions.

Here's the missing step:

cp server/build.properties.example server/build.properties
