### ISSUE TITLE
How to Upgrade

### ISSUE THREAD

**Issue by sah-anshu** [h-mdm/hmdm-server#55]
Hi Team,
I am new to hmdm, i would like to know how to upgrade the existing installation, without losing data.

Thanks in Advance.

**Comment by sah-anshu** [comment]
@vmayorow Looking forward to hear from your side. Every-time a fresh Installation, I am loosing the OLD PostgreSQL Data. Please suggest if i can follow any specific steps to upgrade. 

Thanks in Advance.

**Comment by h-mdm** [comment]
Please follow this instruction to upgrade: https://h-mdm.com/update/

Please note that if you're running the installer, it will always prompt you to erase the database. So, instead of running the installer, just replace the WAR file and restart Tomcat.
