### ISSUE TITLE
PostgreSQL Authentication Error

### ISSUE THREAD

**Issue by t3hchipmunk** [h-mdm/hmdm-server#57]
I am not sure if this is an issue with the server or with the docker container. If docker I will create a case over there instead.

I am receiving the following error. I have added md5 to my pg_hba.conf file running on my postgre instance.

```
Caused by: org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
```

The version of PostgreSQL is `PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`

**Comment by h-mdm** [comment]
Please update the version of Headwind MDM in the Docker configuration files (.env for Docker-Compose, Dockerfile for standalone Docker):
Web panel: 5.06.3 -> 5.10.1
Client (not related to your issue): 5.05 -> 5.10
This should fix the issue (it's recommended to delete all Docker images and reinitialize from scratch).
