### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by sniper9191** [h-mdm/hmdm-server#6]
Hi, I can't seem to install the server.
Running on Ubuntu 19 and Tomcat9.

Getting this error: failed to deploy WAR file!

**Comment by h-mdm** [comment]
The issue could arise because Tomcat 9 works in sandboxed mode and cannot write to any directory. Therefore, when the installer asks for the Headwind MDM directory (defaults to /opt/hmdm), write /var/lib/tomcat9/work instead.

If this won't help, look the Tomcat logs (/var/lib/tomcat9/logs/catalina*.log) to get the error details.

**Comment by theoneandonly-vector** [comment]
Hey there

I got the same issue. Here are the first few lines of log:
'''
02-Jul-2020 14:33:19.268 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.31 (Ubuntu)
02-Jul-2020 14:33:19.269 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 24 2020 22:37:00 UTC
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.31.0
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-37-generic
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.7+10-post-Ubuntu-3ubuntu1
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
02-Jul-2020 14:33:19.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat9
02-Jul-2020 14:33:19.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat9
02-Jul-2020 14:33:19.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat9
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat9
02-Jul-2020 14:33:19.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp
02-Jul-2020 14:33:19.287 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.6.5].
02-Jul-2020 14:33:19.287 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Jul-2020 14:33:19.287 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
02-Jul-2020 14:33:19.290 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1f  31 Mar 2020]
02-Jul-2020 14:33:19.590 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
02-Jul-2020 14:33:19.624 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [596] milliseconds
02-Jul-2020 14:33:19.704 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Jul-2020 14:33:19.705 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.31 (Ubuntu)]
02-Jul-2020 14:33:19.716 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/var/lib/tomcat9/webapps/ROOT]
02-Jul-2020 14:33:20.868 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs th>
02-Jul-2020 14:33:20.901 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [1,185] ms
02-Jul-2020 14:33:20.905 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
02-Jul-2020 14:33:20.918 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,291] milliseconds
02-Jul-2020 14:37:51.923 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:416)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
02-Jul-2020 14:41:31.515 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.undeploy Undeploying context []
02-Jul-2020 14:41:31.550 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/etc/tomcat9/Catalina/localhost/.xml]
02-Jul-2020 14:41:31.552 WARNING [Catalina-utility-2] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] do>
02-Jul-2020 14:41:31.559 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying deployment descriptor [/etc/tomcat9/Catalina/localhost/.xml]
'''

**Comment by theoneandonly-vector** [comment]
when I access the website it tells me:
The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by h-mdm** [comment]
02-Jul-2020 14:41:31.552 WARNING [Catalina-utility-2] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] do>
02-Jul-2020 14:41:31.559 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying deployment descriptor [/etc/tomcat9/Catalina/localhost/.xml]

These lines explain why it wasn't deployed. When the installer script prompts for the installation directory, and you would like to install to the root directory, do not enter empty directory, enter ROOT instead.

So the XML configuration file will be /etc/tomcat8/Catalina/localhost/ROOT.xml.

**Comment by theoneandonly-vector** [comment]
I'm on ubuntu 20.04 with tomcat 9.

and it tries to copy .war file ->  /var/lib/tomcat9/webapps/.war
but there is no "webapps"

**Comment by h-mdm** [comment]
The same issue here: /.war should be /ROOT.war. You need to drop and create empty database, then re-run the installer script.

The directory webapps must exist. This is the directory  for web apps. Did you install Tomcat using apt?

**Comment by theoneandonly-vector** [comment]
yes, I installed using apt

**Comment by theoneandonly-vector** [comment]
another question. if I remove port 8080. Am I able to access it using port 80 and 443?

**Comment by theoneandonly-vector** [comment]
Just installed everything from scratch and it's still not working (this time "webapps" exists already after installing tomcat9)
```
02-Jul-2020 15:26:10.827 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.31 (Ubuntu)
02-Jul-2020 15:26:10.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 24 2020 22:37:00 UTC
02-Jul-2020 15:26:10.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.31.0
02-Jul-2020 15:26:10.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Jul-2020 15:26:10.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-37-generic
02-Jul-2020 15:26:10.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Jul-2020 15:26:10.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
02-Jul-2020 15:26:10.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.7+10-post-Ubuntu-3ubuntu1
02-Jul-2020 15:26:10.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
02-Jul-2020 15:26:10.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat9
02-Jul-2020 15:26:10.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat9
02-Jul-2020 15:26:10.852 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
02-Jul-2020 15:26:10.852 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
02-Jul-2020 15:26:10.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Jul-2020 15:26:10.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties
02-Jul-2020 15:26:10.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Jul-2020 15:26:10.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
02-Jul-2020 15:26:10.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Jul-2020 15:26:10.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Jul-2020 15:26:10.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Jul-2020 15:26:10.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
02-Jul-2020 15:26:10.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat9
02-Jul-2020 15:26:10.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat9
02-Jul-2020 15:26:10.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp
02-Jul-2020 15:26:10.856 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.6.5].
02-Jul-2020 15:26:10.856 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Jul-2020 15:26:10.857 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
02-Jul-2020 15:26:10.860 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1f  31 Mar 2020]
02-Jul-2020 15:26:11.166 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
02-Jul-2020 15:26:11.218 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [646] milliseconds
02-Jul-2020 15:26:11.298 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Jul-2020 15:26:11.298 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.31 (Ubuntu)]
02-Jul-2020 15:26:11.306 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/var/lib/tomcat9/webapps/ROOT]
02-Jul-2020 15:26:12.497 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs th>
02-Jul-2020 15:26:12.534 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [1,228] ms
02-Jul-2020 15:26:12.537 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
02-Jul-2020 15:26:12.559 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,340] milliseconds
02-Jul-2020 15:26:39.707 INFO [http-nio-8080-exec-3] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:416)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
02-Jul-2020 15:33:02.631 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.undeploy Undeploying context []
02-Jul-2020 15:33:02.667 INFO [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/var/lib/tomcat9/webapps/ROOT.war]
02-Jul-2020 15:33:05.653 INFO [Catalina-utility-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete l>
02-Jul-2020 15:33:06.679 INFO [Catalina-utility-2] com.google.inject.internal.MessageProcessor.visit An exception was caught and reported. Message: java.lang.NullPointerException
```

**Comment by theoneandonly-vector** [comment]
last few lines:
```

                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: java.lang.NullPointerException
                at java.base/java.lang.Class.forName0(Native Method)
                at java.base/java.lang.Class.forName(Class.java:315)
                at com.hmdm.guice.module.AbstractLiquibaseModule.getConnection(AbstractLiquibaseModule.java:122)
                ... 51 more
02-Jul-2020 15:39:26.923 INFO [main] nonapi.io.github.classgraph.classloaderhandler.lifecycle.ServletLifeCycleListener.contextInitialized Servlet context initialized
02-Jul-2020 15:39:26.923 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
02-Jul-2020 15:39:26.935 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
02-Jul-2020 15:39:26.938 INFO [main] nonapi.io.github.classgraph.classloaderhandler.lifecycle.ServletLifeCycleListener.contextDestroyed Servlet context destroyed -- closing any remaning open ClassGraph ScanResul>
02-Jul-2020 15:39:26.947 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/var/lib/tomcat9/webapps/ROOT.war] has finished in [4,709] ms
02-Jul-2020 15:39:26.950 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
02-Jul-2020 15:39:26.973 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [4,819] milliseconds
```

**Comment by theoneandonly-vector** [comment]
the exception which keeps happening:
```
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: java.lang.NullPointerException
                at java.base/java.lang.Class.forName0(Native Method)
                at java.base/java.lang.Class.forName(Class.java:315)
                at com.hmdm.guice.module.AbstractLiquibaseModule.getConnection(AbstractLiquibaseModule.java:122)
                ... 51 more
02-Jul-2020 15:39:26.634 INFO [main] com.google.inject.internal.MessageProcessor.visit An exception was caught and reported. Message: java.lang.NullPointerException
        java.lang.RuntimeException: java.lang.NullPointerException
                at com.hmdm.guice.module.AbstractLiquibaseModule.getConnection(AbstractLiquibaseModule.java:130)
```

**Comment by h-mdm** [comment]
Please can you check the contents of the XML configuration file? /var/lib/tomcat8/conf/Catalina/localhost/ROOT.xml
Which is the value of JDBC.driver tag?
Does Tomcat have rights to read the contents of this file?

**Comment by theoneandonly-vector** [comment]
there is nothing inside:
/var/lib/tomcat9/conf/Catalina/localhost

**Comment by theoneandonly-vector** [comment]
drwxr-x--- 2 tomcat tomcat 4096 Jul  2 15:33 localhost

**Comment by h-mdm** [comment]
Did you install using hmdm_install.sh? It should place ROOT.xml into this directory.

Please can you retry the installation (do not forget to remove the database and create an empty one), and if the problem persists (no ROOT.xml in /var/lib/tomcat9/conf/Catalina/localhost), post the installer script (hmdm_install.sh) output here.

**Comment by theoneandonly-vector** [comment]
yes I used hmdm_install.sh

dropped the DB and reinstalled:
```
sudo ./hmdm_install.sh
Please choose the installation language (en/ru) [en]: en

PostgreSQL database setup
=========================
Make sure you've installed PostgreSQL and created the database:
# CREATE USER hmdm WITH PASSWORD 'topsecret';
# CREATE DATABASE hmdm WITH OWNER=hmdm;

PostgreSQL host [localhost]: localhost
PostgreSQL port [5432]: 5432
PostgreSQL database [hmdm]: hmdm
PostgreSQL user [hmdm]: hmdm
PostgreSQL password: jdf98rj9jrmhsdvh42w

File storage setup
==================
Please choose where the files uploaded to Headwind MDM will be stored
If the directory doesn't exist, it will be created
##### FOR TOMCAT 9, USE SANDBOXED DIR: /var/lib/tomcat9/work #####

Headwind MDM directory [/opt/hmdm]: /var/lib/tomcat9/work

Web application setup
=====================
Headwind MDM requires access from Internet
Please assign a public domain name to this server

Protocol (http|https) [http]: http
Domain name or public IP (e.g. example.com): mdm.neutronix.ch
Port (leave empty for default ports 80 or 443): 8080
Project path on server or ROOT [/hmdm]: ROOT
Tomcat virtual host [localhost]: localhost

Ready to install!
Location on server: /var/lib/tomcat9/work
URL: http://mdm.neutronix.ch:8080
Is this information correct [Y/n]? Y
Tomcat config file created: /var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml
Deploying ./server/target/launcher.war to Tomcat: /var/lib/tomcat9/webapps/ROOT.war
............................................................
ERROR: failed to deploy WAR file!
Please check /var/lib/tomcat9/logs/catalina.out for details.
```

ROOT-Folder and ROOT.war do exist inside:
/var/lib/tomcat9/webapps/

**Comment by h-mdm** [comment]
There was an issue in the installation script. Please pull the changes and retry. I tested the new installation script on a fresh Ubuntu 20.04 and Tomcat 9 and everything works well.

**Comment by theoneandonly-vector** [comment]
it works now :)
should I open a new issue for messaging not working? or is this not implemented yet?

**Comment by h-mdm** [comment]
Yes, you can open a new issue. You can also search our QA website: https://qa.h-mdm.com  Search query: mqtt
