### ISSUE TITLE
Does HMDM community edition support server deployment/update of main launcher app?

### ISSUE THREAD

**Issue by shivsingh-aa1** [h-mdm/hmdm-server#60]
Does HMDM community edition support server deployment/update of main launcher app?

The main readme of the repository specifies this as one of the features under the **Features** section.

> Automatic deployment of applications through the web panel

How could we add/update an app via admin panel /GUI and is there any specific procedure to do the same by executing some command on the server (adding the app to some table and executing some code for an update to follow)?

Thanks a lot for your valuable time and for all your efforts put into bringing up this project!

**Comment by h-mdm** [comment]
The main launcher app is updated in the same way as other apps. See details here: https://h-mdm.com/quick-start/#app

**Comment by shivsingh-aa1** [comment]
Should have gone through the quick start page properly earlier.. Thanks a lot for mentioning this!
