### ISSUE TITLE
Trouble with Letsencrypt

### ISSUE THREAD

**Issue by Quaffio69** [h-mdm/hmdm-server#67]
Running into a little trouble getting my deployment running. There's specifically an issue when running the letsencrypt-ssl.sh where the server fails the verification challenge and the script ends. This is strange because it is reachable over WAN unencrypted. I'm attaching the error. tomcat9 running on Ubuntu 20.04 live server with most up to date hmdm. 
![letsencrypterror](https://user-images.githubusercontent.com/36288005/206910292-0979e155-324a-4a46-995c-8d35f535478a.PNG)

**Comment by Quaffio69** [comment]
Some fixes I've already tried
-Syncing time on the bios of the server this is running on
-Forwarding ports 8080,8443 to the hmdm server
-Reinstalling ubuntu and hmdm
-Run hmdm_install.sh many times
-edit build.properties.example to be build.properties

**Comment by h-mdm** [comment]
LetsEncrypt uses port 80 to validate the domain, and certbot temporarily runs nginx to answer the validation request. 

If port 80 is blocked on a firewall or occupied by another program (nginx or Apache), LetsEncrypt will fail.
