### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ll3N1GmAll** [h-mdm/hmdm-server#69]
This is a fresh Ubuntu 20.04 install. Following the instructions here: https://h-mdm.com/advanced-web-panel-installation/

Running the command "mvn install" from step 3 results in the following error:

[INFO] MDM Server ......................................... FAILURE [  0.174 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.885 s
[INFO] Finished at: 2023-01-27T03:32:04-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.7:copy-resources (copy-resources) on project server: Error loading property file 'build.properties': /home/mdm/hmdm-server/server/build.properties -> [Help 1]

It looks like this may be a duplicate issue - https://github.com/h-mdm/hmdm-server/issues/53
However, the BUILD.txt mentions a tomcat8 install. There is no installation candidate for tomcat8 in Ubuntu 20.04.

I did run - cp server/build.properties.example server/build.properties
but during the install process via mvn install, I get the following error messages:

[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ server ---
[INFO] Running 'npm install' in /home/mdm/hmdm-server/server/webtarget
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No description
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No repository field.
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No license field.
[ERROR]
[INFO] added 273 packages from 192 contributors and audited 272 packages in 6.781s
[INFO] found 63 vulnerabilities (4 low, 21 moderate, 32 high, 6 critical)
[INFO] run npm audit fix to fix them, or npm audit for details
[INFO]

Also, can we change the default ports? Can we use a non-commercial certificate that is not Let's Encrypt? The port 80 requirement is a serious hindrance as other services use that port and we are ok with using a self-signed certificate as we have security measures in place to mitigate the risk of a MiTM attack.

**Comment by ll3N1GmAll** [comment]
It looks like this may be a duplicate issue - https://github.com/h-mdm/hmdm-server/issues/53

**Comment by h-mdm** [comment]
This is the duplicate of https://github.com/h-mdm/hmdm-server/issues/53

**Comment by ll3N1GmAll** [comment]
>  Your reply did not address my questions. Once I applied the fix in #53, I got another error. Plus, I had additional setup questions. See below..
... the BUILD.txt mentions a tomcat8 install. There is no installation candidate for tomcat8 in Ubuntu 20.04.

I did run - cp server/build.properties.example server/build.properties
but during the install process via mvn install, I get the following error messages:

[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ server ---
[INFO] Running 'npm install' in /home/mdm/hmdm-server/server/webtarget
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No description
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No repository field.
[WARNING] npm WARN controlled-launcher-webclient@0.1.0 No license field.
[ERROR]
[INFO] added 273 packages from 192 contributors and audited 272 packages in 6.781s
[INFO] found 63 vulnerabilities (4 low, 21 moderate, 32 high, 6 critical)
[INFO] run npm audit fix to fix them, or npm audit for details
[INFO]

Also, can we change the default ports? Can we use a non-commercial certificate that is not Let's Encrypt? The port 80 requirement is a serious hindrance as other services use that port and we are ok with using a self-signed certificate as we have security measures in place to mitigate the risk of a MiTM attack.

**Comment by h-mdm** [comment]
Unfortunately I was unable to reproduce this issue on a fresh Ubuntu 20.04 VM.

Perhaps this could be relevant to your issue: https://stackoverflow.com/questions/16827858/error-npm-warn-package-json-no-repository-field

I kindly ask you not to address multiple issues in one. Add an unique entry with a descriptive subject for each issue. 

For questions not related to issues, please use this platform: https://qa.h-mdm.com.

Let's Encrypt can't use port other than 80, but you can use a commercial certificate and avoid using port 80: https://qa.h-mdm.com/1240/how-to-setup-work-through-https
