### ISSUE TITLE
WAR file not found

### ISSUE THREAD

**Issue by iadrianofp** [h-mdm/hmdm-server#7]
Hi, 

In the folder /hmdm-server/server don't exist any WAR file. 

the script installer fails with error:

'cp: missing destination file operand after '/var/lib/tomcat9/webapps//hmdm.war'

**Comment by h-mdm** [comment]
Did you build the WAR file? Build is done by the following command:

# mvn package

After that, you can install. 

For Tomcat 9, read the installer instructions carefully: you must change the default installation directory!

**Comment by theoneandonly-vector** [comment]
@h-mdm 
hey there
do you have a link for the instructions on tomcat9.
I wasn't able to find it.

**Comment by h-mdm** [comment]
Headwind MDM installer (hmdm_install.sh) works with Tomcat 9. The only difference is that you must change the default installation directory: /opt/hmdm -> /var/lib/tomcat9/work. There's no special instructions for tomcat 9, just follow the installer hints.
