### ISSUE TITLE
Web Panel does not show the applications added by the API in a configuration. 

### ISSUE THREAD

**Issue by Averell7** [h-mdm/hmdm-server#76]
Suppose I have a configuration with four applications, A, B, C, D
1) I use the API to add the applications E and F. The change is OK on the phone, but in the web interface, the applications list is still showing the four applications. The new ones are not there. 
2) I use the API to change the applications to A, B, E, F. The change is OK on the phone. The applications list now shows only two : A and B. 
3) I use the API to change the applications to C, D, E, F. The change is OK on the phone. The applications list is empty. 
4) I use the API to come back to the first configuration with  applications A, B, C, D. The change is OK on the phone. The applications list remains empty. 

The conclusion is simple : the API removes applications from the list when needed, but never adds them. 
It should be simple to fix. 
Thanks

**Comment by h-mdm** [comment]
Headwind MDM web panel uses the same API to manage applications in the configuration, so it is not possible that API doesn't add applications (otherwise the web panel would not work as expected). 

You can try managing applications in the configuration, keeping Chrome console opened as suggested here: https://qa.h-mdm.com/16735/  Then you can compare your API calls and sample calls of the web panel. Perhaps this helps you to resolve the issue.

**Comment by Averell7** [comment]
The problem is not with the API, as I said on the phone it works perfectly, so the applications are really added, no problem there. The problem is on the web panel which does not take the information and is not updated correctly. It is a display problem, not an API problem.

**Comment by Averell7** [comment]
Is there a parameter in the API call which is necessary to display the added applications to the list ? Maybe I missed something there ? 
I will provide the API call.

**Comment by Averell7** [comment]
[payload.txt](https://github.com/h-mdm/hmdm-server/files/11060574/payload.txt)
![2023-03-24_104312](https://user-images.githubusercontent.com/858359/227484358-28cb9375-c7da-45fa-af29-653fad9f00f6.png)
All applications are present on the phone, in the web panel only two applications are shown, because I had added them manually to the applications before I used the API. To be precise : I added 3, and 2 remains because the third one was not present in the selection sent with the API.
code is : 
```
def put(path, payload):
    global token
    command = ["curl", "-s", "-X",
           "PUT", "https://mdm.sheltercom.net:8443/rest" + path,
           "-H",  "Content-Type: application/json",
           "-H",  "Authorization: Bearer %s" % token,
           "-d",  payload
           ]
    #print("\n ===> command :", command[0:19], "\n")
    x = subprocess.check_output(command) 
    return x.decode("utf-8")

x = put("/private/configurations", payload)
```

**Comment by Averell7** [comment]
The answer to the above question is yes. The "action" parameter must be set to 1, otherwise the applications do not appear in the applications list of the configuration. Once set to 1, they are there. 
Good to know. 
I close the issue, thanks for your answers.
