### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by larsziegelmann** [h-mdm/hmdm-server#8]
I'm having issues with accessing the web interface after following the installation instructions.

I have installed and checked if Tomcat9 is working properly with the command: `telnet localhost 8080`
I have built the source code with the command: `mvn package`
I also created the PostgreSQL user(hmdm) and database(hmdm).
After running the script with root, there were no error messages. I tried connecting to the domain I have typed in but it displays connection refused on Chrome.

Is there any log file I can send for you to look at?

**Comment by h-mdm** [comment]
Did you specify port 8080 in the URL? Example: http://app.h-mdm.com:8080 not http://app.h-mdm.com ?

This link could be also helpful to you: https://qa.h-mdm.com/1533/how-to-run-headwind-mdm-on-ports-80-or-443

**Comment by Zoinzibar** [comment]
at the end of the script when it require to say [Y or n] enter "y" because the script don't understand when you just hit enter with nothing
That worked for me

**Comment by blazenn12** [comment]
Did you install hmdm with DEFAULT_BASE_PATH? ("/hmdm")
You can try http://<host>:<port>/hmdm
