### ISSUE TITLE
failed to deploy WAR file

### ISSUE THREAD

**Issue by JIKJA** [h-mdm/hmdm-server#80]
First I tried the mdm installation guide and it worked for me. 
However, when reinstalling the server using hmdm_install.sh, the error "failed to deploy WAR file" appeared. It seems that the script does not clean up the hmdm database completely and leaves the usagestats, pendingsignup, plugin_push_messages tables. 
Adding these tables to the script solved the problem.

**Comment by h-mdm** [comment]
Thank you for the info. The tables have been added to the installer script.
