### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [h-mdm/hmdm-server#82]
Dear @h-mdm team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by h-mdm** [comment]
The topic you're talking about doesn't seem to be related to any Headwind MDM issue. We kindly ask you to raise an issue only if you are having problems with Headwind MDM software, thank you for understanding.

**Comment by Neustradamus** [comment]
@h-mdm: Can you read the request?

It is a problem with @h-mdm.

**Comment by h-mdm** [comment]
We appreciate your inquiry and will consider to go further in the future. Since this is a purely organizational inquiry which is not related to the Headwind MDM functionality and quality, we keep it on hold by now.

**Comment by Neustradamus** [comment]
Dear @h-mdm,

Have you progressed on this ticket?

Thanks in advance.
