### ISSUE TITLE
Qr code not open

### ISSUE THREAD

**Issue by safalbhatia** [h-mdm/hmdm-server#89]
When i click on QR Code then My QrCode not show and After Click go to my server login URL.  
![Untitled](https://github.com/h-mdm/hmdm-server/assets/27086730/b83753b7-d705-4be8-9e4d-e4d6ca00a757)

**Comment by h-mdm** [comment]
Please check out this help article: https://qa.h-mdm.com/1/installed-the-system-but-qr-code-is-not-showing
