### ISSUE TITLE
reporting wrong version

### ISSUE THREAD

**Issue by mbols2510** [h-mdm/hmdm-server#91]
we started with version 5.22.1 for the web panel, but we wanted to update it to 5.24.1 but even after completing the update script, it keeps sying we are on version 5.22.1 when in the logs the wab panel is using version 5.24.1
![Schermafbeelding 2023-12-08 103804](https://github.com/h-mdm/hmdm-server/assets/70890664/03c6bdfb-544b-4f22-8dbc-0ff94da774fc)
![Schermafbeelding 2023-12-08 103701](https://github.com/h-mdm/hmdm-server/assets/70890664/1f5bd2cd-724d-4a2f-b640-138aa70e0f09)

**Comment by h-mdm** [comment]
To finalize the web panel update, run the script:

/opt/hmdm/update-web-app.sh

After the update, clear the browser cache and refresh the webpage (Ctrl-F5 in Chrome).
