### ISSUE TITLE
System update on Pixel Tablet does not work

### ISSUE THREAD

**Issue by TommyTran732** [h-mdm/hmdm-server#92]
I noticed that system update on the Pixel Tablet, even when set to "immediate", does not work. The Tablet will be stuck in Android 13 and will not even update to Android 14.

**Comment by h-mdm** [comment]
Headwind MDM doesn't update the OS. It configures the OS update policy by using the method DevicePolicyManager.setSystemUpdatePolicy(). If OS doesn't follow this policy, Headwind MDM can do nothing with that.

**Comment by TommyTran732** [comment]
You are right. This appears to be a bug with the OS originally shipped with the Pixel Tablet. I checked again and the Pixel Tablet gets updates just fine on Android 14.
