### ISSUE TITLE
Setting homepage for Edge browser

### ISSUE THREAD

**Issue by Tualua** [h-mdm/hmdm-server#93]
Hello! Is there any way to set homepage for browser?

**Comment by h-mdm** [comment]
MDM application has no access to third party app settings. It can only manage settings for applications integrated with Headwind MDM. So I'm afraid it's not possible to manage Edge home page. 

Premium package includes a Kiosk Browser where a home page can be configured. To get a free trial of Headwind MDM Premium, please submit the contact form: https://h-mdm.com/contact-us/
