### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by BrainDawson** [h-mdm/hmdm-server#95]
After installation, entering admin login on the page will prompt for an invalid username and password. Why is this?

**Comment by h-mdm** [comment]
After the installation, the default credentials are admin:admin (the system will prompt to change the admin password at first start). Avoid using copy-paste when filling in the credentials: copying and pasting may insert extra spaces in the password which will cause the "Invalid username or password" error.

**Comment by BrainDawson** [comment]
I have already used the default credentials(admin: admin) and typed it myself, but there may still be errors with invalid username and password. What other steps could have caused this error?

**Comment by BrainDawson** [comment]
I have already used the default credentials(admin:admin) and typed it myself, but there may still be errors with invalid username and password. What other steps could have caused this error?
