### ISSUE TITLE
Cant be reached error when trying to generate QR code

### ISSUE THREAD

**Issue by sanjog-nosh** [h-mdm/hmdm-server#96]
ERROR: "This site can’t be reached"
This is the error I am getting , the dashboard is working , but on generating the qr we are facing this problem

We tried using different ports but every time the dashboard link is made with 8080. when we tried to wget the installer then we unable to establish SSL connection

**Comment by h-mdm** [comment]
To get answers on installation issues, please use the following Q&A website: https://qa.h-mdm.com

The URL used in the QR code is managed in the XML config file: /var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml

Probably this article is related to your issue: https://qa.h-mdm.com/1/installed-the-system-but-qr-code-is-not-showing
